[package]
name = "pbrt"
version = "0.1.0"
authors = ["Bill Thiede <rust@xinu.tv>"]

[dependencies]
getopts = "0.2.15"
nom = "3.2.1"
regex = "0.2.5"
log = "0.4.1"
env_logger = "0.4.3"
simplelog = "0.4.4"
structopt = "0.1.7"
structopt-derive = "0.1.6"

